FEATURES = ['gender',
 'Alanine_aminotransferase_[Enzymatic_activity/volume]_in_Serum_or_Plasma',
 'Albumin_[Mass/volume]_in_Serum_or_Plasma',
 'Alkaline_phosphatase_[Enzymatic_activity/volume]_in_Serum_or_Plasma',
 'American_house_dust_mite_IgE_Ab_in_Serum',
 'Appearance_of_Urine',
 'Aspartate_aminotransferase_[Enzymatic_activity/volume]_in_Serum_or_Plasma',
 'Bilirubin.total_[Mass/volume]_in_Serum_or_Plasma',
 'Bilirubin.total_[Mass/volume]_in_Urine_by_Test_strip',
 'Bilirubin.total_[Presence]_in_Urine_by_Test_strip',
 'Blood_Pressure',
 'Body_Height',
 'Body_Mass_Index',
 'Body_Weight',
 'Calcium',
 'Carbon_Dioxide',
 'Cat_dander_IgE_Ab_in_Serum',
 'Cause_of_Death_[US_Standard_Certificate_of_Death]',
 'Chloride',
 'Cladosporium_herbarum_IgE_Ab_in_Serum',
 'Clarity_of_Urine',
 'Codfish_IgE_Ab_in_Serum',
 'Color_of_Urine',
 'Common_Ragweed_IgE_Ab_in_Serum',
 'Cow_milk_IgE_Ab_in_Serum',
 'Creatinine',
 'DXA_[T-score]_Bone_density',
 'Egg_white_IgE_Ab_in_Serum',
 'Erythrocyte_distribution_width_[Entitic_volume]_by_Automated_count',
 'Erythrocytes_[#/volume]_in_Blood_by_Automated_count',
 'Estimated_Glomerular_Filtration_Rate',
 'FEV1/FVC',
 'Globulin_[Mass/volume]_in_Serum_by_calculation',
 'Glomerular_filtration_rate/1.73_sq_M.predicted',
 'Glucose',
 'Glucose_[Mass/volume]_in_Urine_by_Test_strip',
 'Glucose_[Presence]_in_Urine_by_Test_strip',
 'Hematocrit_[Volume_Fraction]_of_Blood',
 'Hematocrit_[Volume_Fraction]_of_Blood_by_Automated_count',
 'Hemoglobin.gastrointestinal_[Presence]_in_Stool_by_Immunologic_method',
 'Hemoglobin_A1c/Hemoglobin.total_in_Blood',
 'Hemoglobin_[Mass/volume]_in_Blood',
 'Hemoglobin_[Presence]_in_Urine_by_Test_strip',
 'High_Density_Lipoprotein_Cholesterol',
 'History_of_Hospitalizations+Outpatient_visits',
 'Honey_bee_IgE_Ab_in_Serum',
 'Ketones_[Mass/volume]_in_Urine_by_Test_strip',
 'Ketones_[Presence]_in_Urine_by_Test_strip',
 'Latex_IgE_Ab_in_Serum',
 'Leukocyte_esterase_[Presence]_in_Urine_by_Test_strip',
 'Leukocytes_[#/volume]_in_Blood_by_Automated_count',
 'Low_Density_Lipoprotein_Cholesterol',
 'MCHC_[Mass/volume]_by_Automated_count',
 'MCH_[Entitic_mass]_by_Automated_count',
 'MCV_[Entitic_volume]_by_Automated_count',
 'Mental_health_Outpatient_Note',
 'Mental_health_Telehealth_Note',
 'Microalbumin_Creatinine_Ratio',
 'Nitrite_[Presence]_in_Urine_by_Test_strip',
 'Odor_of_Urine',
 'Oral_temperature',
 'Pain_severity_-_0-10_verbal_numeric_rating_[Score]_-_Reported',
 'Peanut_IgE_Ab_in_Serum',
 'Percentage_area_affected_by_eczema_Head_and_Neck',
 'Percentage_area_affected_by_eczema_Lower_extremitiy_-_bilateral',
 'Percentage_area_affected_by_eczema_Trunk',
 'Percentage_area_affected_by_eczema_Upper_extremitiy_-_bilateral',
 'Physical_findings_of_Prostate',
 'Platelet_distribution_width_[Entitic_volume]_in_Blood_by_Automated_count',
 'Platelet_mean_volume_[Entitic_volume]_in_Blood_by_Automated_count',
 'Platelets_[#/volume]_in_Blood_by_Automated_count',
 'Polyp_size_greatest_dimension_by_CAP_cancer_protocols',
 'Potassium',
 'Prostate_specific_Ag_[Mass/volume]_in_Serum_or_Plasma',
 'Protein_[Mass/volume]_in_Serum_or_Plasma',
 'Protein_[Mass/volume]_in_Urine_by_Test_strip',
 'Protein_[Presence]_in_Urine_by_Test_strip',
 'Shrimp_IgE_Ab_in_Serum',
 'Sodium',
 'Soybean_IgE_Ab_in_Serum',
 'Specific_gravity_of_Urine_by_Test_strip',
 'Thyrotropin_[Units/volume]_in_Serum_or_Plasma',
 'Thyroxine_(T4)_free_[Mass/volume]_in_Serum_or_Plasma',
 'Tobacco_smoking_status_NHIS',
 'Total_Cholesterol',
 'Total_score_[MMSE]',
 'Triglycerides',
 'US_Guidance_for_biopsy_of_Prostate',
 'Urea_Nitrogen',
 'Veterans_Rand_health_survey_-_36_item_(VR-36)',
 'Walnut_IgE_Ab_in_Serum',
 'Weight_difference_[Mass_difference]_--pre_dialysis_-_post_dialysis',
 'Wheat_IgE_Ab_in_Serum',
 'White_oak_IgE_Ab_in_Serum',
 'others',
 'pH_of_Urine_by_Test_strip']

MAP_FEATURES = {
    'Albumin_SerPl-mCnc': 'Albumin_[Mass/volume]_in_Serum_or_Plasma',
    'Systolic_blood_pressure': 'Blood_Pressure',
    'Calcium_SerPl-mCnc': 'Calcium',
    'bmi': 'Body_Mass_Index',
    'weight': 'Body_Weight',
    'MCHC_RBC_Auto-mCnc': 'Erythrocytes_[#/volume]_in_Blood_by_Automated_count',
    'Glucose_SerPl-mCnc': 'Glucose',
    'WBC_#/area_UrnS_HPF': 'Leukocyte_esterase_[Presence]_in_Urine_by_Test_strip',
    'Platelet_#_Bld': 'Platelets_[#/volume]_in_Blood_by_Automated_count',
    'temperature': 'Oral_temperature'
 }